source 'https://rubygems.org'
 gem 'rails', '4.1.11'
 gem 'pg'
 gem 'figaro'
 gem 'jquery-rails'
 gem 'turbolinks'
 gem 'mailgun-ruby', '~>1.0.2', require: 'mailgun'
 gem 'activejob_backport'
 gem 'delayed_job_active_record'
 gem 'unicorn'
 gem 'foreman'
 gem 'rabl'
 gem 'oj'
 gem 'paranoia', '~> 2.0'
 gem 'friendly_id', '~> 5.1.0'
 gem 'devise'
 gem 'devise-encryptable'
 gem 'omniauth'
 gem 'omniauth-google-oauth2'
 gem 'foundation-rails'
 gem 'paperclip', '~> 4.3'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'spring-commands-rspec'
  gem 'selenium-webdriver'
  gem 'pry'
  gem 'database_cleaner'
end

group :test do
  gem 'codeclimate-test-reporter'
end
group :development do
  gem 'pivotal_git_scripts'
end

group :production do

end
