source "https://rubygems.org"
 gem "rails", '4.1.3'
 gem 'pg'


group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'spring-commands-rspec'
  gem 'selenium-webdriver'
  gem 'pry'
  gem 'database_cleaner'
end

group :development do
  gem 'pivotal_git_scripts'
end

group :production do

end